"""Direct ComfyUI HTTP transport. Replaces comfy_api_simplified.

Results come from the jobs API: GET /api/jobs/{id}. Older ComfyUI builds may lack
that route, so a 404 falls back to GET /api/history/{id}. The websocket (see
progress()) carries progress events only. This separation is not stylistic:
treating websocket binary frames as results produced two silent-wrong-result bugs
in this pipeline's history (a step preview returned as the final image; an
85-byte HTML caption fragment returned instead of a 1MB mp4). Reading results
from the job/history record makes that class of bug structurally impossible."""
import time
import uuid
from pathlib import Path

import requests

from .errors import ComfyrackError, NotFoundError


class ComfyClient:
    def __init__(self, url: str, session=None, poll_interval: float = 1.0):
        self.url = url.rstrip("/")
        self.session = session or requests.Session()
        self.poll_interval = poll_interval
        self.client_id = str(uuid.uuid4())
        self._object_info: dict | None = None
        self._scoped: dict = {}

    # -- transport ---------------------------------------------------------

    def _request(self, method: str, path: str, **kw):
        """Every HTTP call funnels through here so no `requests` exception escapes
        as a raw traceback.

        Uncaught, a dead port surfaced as `UNCAUGHT: requests.exceptions.
        ConnectionError` on stderr with an empty stdout -- violating three output
        contracts at once (errors on stdout, structured shape, actionable `help:`)
        on the single most common runtime failure there is. Wrapping happens HERE,
        at the transport boundary, not above it: the typed errors the rest of this
        module raises (execution errors, timeouts, missing outputs) keep their own
        vocabulary and are untouched.

        `return_error_response=True` opts a call out of the raise: an HTTP error
        response is handed back to the caller instead, so a body that carries
        detail (a 400's node_errors, a 404 from a route this build lacks) can be
        read. The guarantee is unchanged -- no raw `requests` exception escapes
        either way."""
        return_error_response = kw.pop("return_error_response", False)
        url = f"{self.url}{path}"
        fn = self.session.get if method == "GET" else self.session.post
        try:
            r = fn(url, **kw)
            r.raise_for_status()
        except requests.HTTPError as exc:
            if return_error_response and getattr(exc, "response", None) is not None:
                return exc.response
            status = getattr(getattr(exc, "response", None), "status_code", "?")
            raise self._http_error(method, url, status) from exc
        except requests.RequestException as exc:
            raise ComfyrackError(
                f"cannot reach ComfyUI at {url}: {type(exc).__name__}",
                help_text=f"start ComfyUI or check the URL, then "
                          f"`comfyrack stats --machine <name>`; current target is {self.url}",
            ) from exc
        return r

    def _http_error(self, method: str, url: str, status) -> ComfyrackError:
        """The one HTTP-error message, shared by _request's raise and by callers
        that opted into reading an error response and met a status that is not
        the one they were looking for."""
        return ComfyrackError(
            f"ComfyUI returned HTTP {status} for {method} {url}",
            help_text=f"comfyrack stats --machine <name>  # confirm {self.url} is the right target",
        )

    # -- submission --------------------------------------------------------

    def queue_prompt(self, graph: dict, client_id: str | None = None,
                     prompt_id: str | None = None) -> str:
        """POST /api/prompt with a client-chosen prompt_id.

        The prompt_id is generated by the CALLER (submit() makes one before it
        starts the progress pump, so the pump and the poll agree on the id before
        the job exists) and defaults to a fresh uuid. What is sent is what is
        returned: the caller must poll the id it handed to wait(), not a value
        parsed off the response."""
        client_id = client_id or self.client_id
        prompt_id = prompt_id or str(uuid.uuid4())
        r = self._request("POST", "/api/prompt",
                          json={"prompt": graph, "client_id": client_id,
                                "prompt_id": prompt_id},
                          timeout=30, return_error_response=True)
        if r.status_code == 400:
            raise ComfyrackError(self._prompt_rejection_message(r))
        return prompt_id

    @staticmethod
    def _prompt_rejection_message(response) -> str:
        """Flatten a 400 body into the error. That body is the one place ComfyUI
        says WHICH node is wrong and why; reducing it to "HTTP 400" is the
        difference between "fix node 3" and "retry forever"."""
        try:
            body = response.json()
        except ValueError:
            body = None
        if not isinstance(body, dict):
            body = {}
        err = body.get("error") or {}
        server_msg = err.get("message") if isinstance(err, dict) else err
        parts = [f"ComfyUI rejected the prompt: {server_msg}" if server_msg
                 else "ComfyUI rejected the prompt"]
        for node_id, info in (body.get("node_errors") or {}).items():
            if not isinstance(info, dict):
                parts.append(f"node {node_id}: {info}")
                continue
            for e in info.get("errors", []):
                line = f"node {node_id} ({info.get('class_type', '?')}): {e.get('message', '')}"
                if e.get("details"):
                    line = f"{line} {e['details']}"
                parts.append(line)
        return "; ".join(parts)

    def wait(self, prompt_id: str, timeout_s: int = 1800) -> dict:
        """Poll the job record until it reaches a terminal status, then return
        the /history-shaped entry the rest of the code reads.

        GET /api/jobs/{id} is the maintained route. A 404 means this build
        predates it, and the poll falls back to GET /api/history/{id} for the
        rest of the wait -- the route will not appear mid-wait, so the fallback
        is sticky rather than paying a 404 on every poll."""
        deadline = time.time() + timeout_s
        use_history = False
        while True:
            if use_history:
                r = self._request("GET", f"/api/history/{prompt_id}", timeout=30)
                hist = r.json()
                if prompt_id in hist:
                    entry = hist[prompt_id]
                    self._raise_on_execution_error(entry)
                    return entry
            else:
                r = self._request("GET", f"/api/jobs/{prompt_id}", timeout=30,
                                  return_error_response=True)
                if r.status_code == 404:
                    use_history = True
                    continue
                if r.status_code != 200:
                    # Not a missing route -- a 500 or similar. Give it the
                    # standard HTTP-error vocabulary rather than parsing an
                    # error body as a job (which would also let a non-JSON
                    # body raise a raw JSONDecodeError out of wait()).
                    raise self._http_error(
                        "GET", f"{self.url}/api/jobs/{prompt_id}", r.status_code)
                job = r.json()
                status = job.get("status")
                if status in ("completed", "failed", "cancelled"):
                    entry = {"outputs": job.get("outputs", {}),
                             "status": job.get("execution_status") or {}}
                    self._raise_on_execution_error(entry)
                    if status != "completed":
                        raise ComfyrackError(
                            f"workflow {prompt_id} was {status} and reported "
                            f"no execution error")
                    return entry
            if time.time() >= deadline:
                raise ComfyrackError(
                    f"workflow {prompt_id} did not finish within {timeout_s}s",
                    help_text="comfyrack queue  # check whether it is still running",
                )
            time.sleep(self.poll_interval)

    @staticmethod
    def _raise_on_execution_error(entry: dict) -> None:
        for msg in entry.get("status", {}).get("messages", []):
            if msg and msg[0] == "execution_error":
                detail = msg[1]
                text = detail.get("exception_message", detail) if isinstance(detail, dict) else detail
                raise ComfyrackError(f"ComfyUI execution error: {text}")

    @staticmethod
    def outputs(entry: dict, node_id: str) -> list:
        node_out = entry.get("outputs", {}).get(node_id, {})
        for key in ("images", "gifs", "audio", "video"):
            if key in node_out:
                return node_out[key]
        if "text" in node_out:  # PreviewAny and other ui-text nodes
            val = node_out["text"]
            return val if isinstance(val, list) else [val]
        if "string" in node_out:
            val = node_out["string"]
            return val if isinstance(val, list) else [val]
        raise ComfyrackError(
            f"no images/gifs/audio/text in outputs[{node_id!r}]; found keys: "
            f"{sorted(node_out.keys())}",
            help_text="check the manifest's output_node_title names the right node",
        )

    # -- retrieval ---------------------------------------------------------

    def history(self, prompt_id: str) -> dict:
        """GET /api/history/{prompt_id} -- the entry for one prompt.

        The body is keyed by prompt id; an id the server has no record of
        comes back as an empty dict rather than a 404, so the key check below
        is what distinguishes "no such prompt" from "prompt with no outputs".
        The empty dict is raised as a NotFoundError naming the id: returned
        bare, it would read as a successful prompt that happened to produce
        nothing, and `comfyrack outputs` would answer `count: 0` for a typo."""
        r = self._request("GET", f"/api/history/{prompt_id}", timeout=30)
        hist = r.json()
        if prompt_id not in hist:
            raise NotFoundError(
                f"no history entry for prompt {prompt_id!r} on this machine",
                help_text="comfyrack queue  # check whether it is still running",
            )
        return hist[prompt_id]

    def view(self, filename: str, subfolder: str = "", type_: str = "output") -> bytes:
        r = self._request("GET", "/api/view",
                          params={"filename": filename, "subfolder": subfolder,
                                  "type": type_},
                          timeout=120)
        return r.content

    def upload_image(self, path) -> str:
        p = Path(path)
        with open(p, "rb") as fh:
            r = self._request("POST", "/api/upload/image",
                              files={"image": (p.name, fh)},
                              data={"overwrite": "true"}, timeout=120)
        data = r.json()
        # A cached /object_info predates this file, so preflight would reject it
        # as not in the loader's combo options.
        self.refresh_object_info()
        sub = data.get("subfolder", "")
        return f"{sub}/{data['name']}" if sub else data["name"]

    # -- introspection -----------------------------------------------------

    def object_info(self, class_type: str | None = None, timeout: int = 60) -> dict:
        """Memoized per client. On a real ComfyUI with a normal custom-node
        load-out this response is multiple MB, and one `comfyrack run` fetched it
        twice (load_graph, then preflight_graph). Cache the unfiltered result and
        serve a class_type-scoped call out of it, so a scoped call never has to
        re-fetch either. Call refresh_object_info() after installing a node."""
        if class_type is None:
            if self._object_info is None:
                self._object_info = self._request("GET", "/api/object_info",
                                                  timeout=timeout).json()
            return self._object_info
        # A scoped call is served from the full cache when it is warm, and otherwise
        # still hits the scoped endpoint -- promoting it to a full fetch would make
        # a lone `comfyrack node KSampler` download megabytes to read one entry.
        if self._object_info is not None and class_type in self._object_info:
            return {class_type: self._object_info[class_type]}
        if class_type not in self._scoped:
            self._scoped[class_type] = self._request(
                "GET", f"/api/object_info/{class_type}", timeout=timeout).json()
        return self._scoped[class_type]

    def refresh_object_info(self) -> None:
        """Drop the cache. Node definitions change when a custom node is installed
        or ComfyUI restarts, and a long-lived Rack would otherwise never notice."""
        self._object_info = None
        self._scoped = {}

    def embeddings(self) -> list:
        """GET /api/models/embeddings -- the JSON route for the textual-inversion list.

        NOT `/embeddings`. server.py does define a JSON handler at that bare path,
        but on a real ComfyUI (verified against 0.28.0) it is shadowed by the
        frontend, which answers 200 with a 185KB "Embedding Models" HTML page.
        Reading the route decorator is not enough here; only a round trip against a
        running server distinguishes the two, and this package got it wrong once by
        trusting the source alone.

        `/models/{folder}` is the general model-folder route (`/models` lists the
        folder names). It returns `folder_paths.get_filename_list(folder)`
        VERBATIM -- extensions included, and subfolder-organised entries carrying
        their OS-native separator (`Anima\\AnimaEditV1.safetensors` on Windows).
        That differs from the shadowed `/embeddings` handler, which stripped
        extensions; nothing here re-strips them, because the only honest source for
        that shape is a machine with embeddings actually installed.

        A body that is not JSON is raised as a ComfyrackError rather than a bare
        requests JSONDecodeError: `_request` guarantees no raw requests exception
        reaches a caller, and .json() happens after it returns, outside that guard.
        Turning it into a typed error is also what lets discover.embeddings() fall
        back to /object_info on a build that shadows this path too."""
        r = self._request("GET", "/api/models/embeddings", timeout=30)
        try:
            return r.json()
        except ValueError as exc:
            raise ComfyrackError(
                f"{self.url}/api/models/embeddings did not return JSON "
                f"({getattr(r, 'text', '')[:40]!r}...)",
                help_text="this build may serve that path as a web page; "
                          "comfyrack models --machine <name> still lists checkpoints "
                          "and loras",
            ) from exc

    def queue_status(self) -> dict:
        return self._request("GET", "/api/queue", timeout=30).json()

    def system_stats(self) -> dict:
        return self._request("GET", "/api/system_stats", timeout=30).json()

    def interrupt(self) -> None:
        self._request("POST", "/api/interrupt", timeout=30)

    # -- progress ----------------------------------------------------------

    def progress(self, prompt_id: str, on_event, ws_factory=None,
                 client_id: str | None = None) -> None:
        """Stream progress events for prompt_id until it finishes.

        Binary frames are DISCARDED without inspection. This channel never returns
        a result -- results come from wait()/outputs() over the job/history record.
        Treating a websocket binary frame as a result is precisely the bug this
        design exists to make impossible."""
        import json as _json

        client_id = client_id or self.client_id
        if ws_factory is None:
            def ws_factory(url):
                import websocket
                return websocket.create_connection(url, timeout=60)

        ws_url = self.url.replace("https://", "wss://").replace("http://", "ws://")
        ws = ws_factory(f"{ws_url}/ws?clientId={client_id}")
        try:
            while True:
                try:
                    frame = ws.recv()
                except Exception:
                    # Deliberately broad. websocket-client raises
                    # WebSocketConnectionClosedException on a dropped connection, which
                    # inherits from Exception, NOT OSError -- so `except (ConnectionError,
                    # OSError)` misses the single most common real failure and lets it
                    # escape progress(). Over-catching is safe here precisely because this
                    # channel never carries results: the worst case is an early clean
                    # return, and wait()/history still produces the real output.
                    return
                if not isinstance(frame, str):
                    continue  # binary preview payload -- never a result
                try:
                    event = _json.loads(frame)
                except ValueError:
                    continue
                if not isinstance(event, dict):
                    continue  # valid JSON, wrong shape (bare string/number/array)
                data = event.get("data") or {}
                if data.get("prompt_id") not in (None, prompt_id):
                    continue
                on_event(event)
                if event.get("type") == "executing" and data.get("node") is None:
                    return
        finally:
            try:
                ws.close()
            except Exception:
                pass
